#26 - update to compatibility with laravel 11
blumilksoftware/blt pull request #29
Opened 2024-06-05 07:05 UTC by JakubKermes

Bumped dependencies. Based on Laravel [documentation](https://laravel.com/docs/11.x/upgrade) for upgrading Laravel, there is no need for changing any code.

2024-06-06 06:12 UTC, orlowski11 commented on composer.json
There is some kind of problem with this, check slack for more information.

2024-06-06 06:32 UTC, JakubKermes commented on composer.json
Hey, are you sure this is about this branch?

2024-06-06 07:03 UTC, orlowski11 approved these changes

2024-06-06 07:51 UTC, krzysztofrewak requested changes

2024-06-06 07:51 UTC, krzysztofrewak commented on composer.json
> +  "name":"blumilksoftware/blt",
Why did you removed a space here?

2024-06-06 08:55 UTC, JakubKermes commented on composer.json
> +  "name":"blumilksoftware/blt",
Sorry, fixed

2024-06-06 13:03 UTC, krzysztofrewak requested changes

2024-06-06 13:03 UTC, krzysztofrewak commented on composer.json
> +    "symfony/http-foundation": "^6.2|^7.1"
I think you can stay with `"^10.0|11.9"` or even `"^10.0|11.0"` if there's no big changes in 11.1.

2024-06-07 08:58 UTC, PiotrFedak approved these changes

2024-06-07 11:47 UTC, krzysztofrewak approved these changes

2024-06-07 11:57 UTC, merged