#4 - Add console testing tools
blumilksoftware/blt pull request #31
Opened 2024-06-05 09:49 UTC by JakubKermes

Added basic tools for testing artisan and shell commands to be extended in the future.
It would be nice to support prompts for more information in conversation like style:
```php
@console
    Feature: Console conversation test
        Scenario: Test Artisan command
            Given I run artisan command "make:model" with argument "TestModel"
            Then I am asked "Would you like any of the following?"
            And I select "Factory"
```

2024-06-07 11:58 UTC, krzysztofrewak requested changes

2024-06-07 11:58 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +        exec($command, $output);
I'm not sure if using exec in tests is a good idea. I would remove this method as possible violation of security of the application.

2024-06-07 12:01 UTC, krzysztofrewak requested changes

2024-06-07 12:01 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +        Artisan::call($command);
Please get artisan console from the dependency container. We should not use facades in packages as described here: https://laravel.com/docs/11.x/packages#a-note-on-facades

2024-06-07 12:01 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +        $this->runArtisanCommand("$command $arguments");
Will it work with multiple arguments?

2024-06-19 09:32 UTC, krzysztofrewak commented
@JakubKermes, could you merge current main into the branch before my second review? It looks like some files are outdated.

2024-06-21 01:58 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +        $this->runArtisanCommand("$command $arguments");
Wouldn't table be easier to use?

2024-06-21 06:27 UTC, JakubKermes commented on src/Features/Traits/Console.php
> +        $this->runArtisanCommand("$command $arguments");
Probably it would. I'll look into it

2024-06-24 07:00 UTC, krzysztofrewak requested changes

2024-06-24 07:00 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +     * @Then I see :output in console
I don't see any other occurences of `@Then I...` in the codebase. Please be consistent with phrasing. 

I don't mean that's a wrong approach. But it should be same in all methods, so please discuss how should be handle this.

2024-07-01 08:05 UTC, krzysztofrewak requested changes

2024-07-01 08:05 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +     * @Given I run artisan command :command in console
```suggestion
     * @Given a command :command is ran
     * @Given a command :command is ran in console
```

2024-07-01 08:05 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +     * @Given I run artisan command :command with:
```suggestion
     * @Given a command :command is ran with:
```

2024-07-01 08:05 UTC, krzysztofrewak commented on src/Features/Traits/Console.php
> +        $this->consoleOutput = $this->getContainer()->make(Kernel::class)->output();
```suggestion
        $console = $this->getContainer()->make(Kernel::class);
        $this->consoleCode = $console->call($command);
        $this->consoleOutput = $console->output();
```

2024-07-01 11:44 UTC, krzysztofrewak approved these changes

2024-07-01 11:45 UTC, merged