model relations tools added
blumilksoftware/blt pull request #42
Opened 2024-06-07 19:04 UTC by PiotrFedak

This PR adds new functions to the eloquent trait.

- Creates a model if it does not exist as data.
- Creates the specified number of models if they are missing.
- Checking relationships between models.

2024-06-11 08:24 UTC, krzysztofrewak requested changes

2024-06-11 08:24 UTC, krzysztofrewak commented on src/Features/Traits/Eloquent.php
> +     * @Given there is a :model in the database
Maybe table with parameters that you could provide to factory's `create()` method would be handy?

2024-06-11 08:24 UTC, krzysztofrewak commented on src/Features/Traits/Eloquent.php
> +            'Illuminate\Database\Eloquent\Relations\HasOne',
Maybe you could move it to class with other Laravel classes?

2024-06-11 08:24 UTC, krzysztofrewak commented on src/Features/Traits/Eloquent.php
> +        Assert::assertTrue($modelClass::query()->exists(), "The model $model does not exist in the database.");
Oh, I don't get what's going on here.

Should this method be used to seed database or check database?

2024-06-14 12:49 UTC, JakubKermes commented
Maybe we should add creating for models without factory?

2024-06-14 12:54 UTC, JakubKermes commented on src/Features/Traits/Eloquent.php
> +        $modelClass::factory()->create($attributes);
Maybe we should add creating for models without factory?

2024-06-24 06:56 UTC, krzysztofrewak requested changes

2024-06-24 06:56 UTC, krzysztofrewak commented on src/Features/Traits/Eloquent.php
> +        LaravelRelations::assertRelation($instance, $relation, 'Illuminate\Database\Eloquent\Relations\HasMany');
Please look at this file: https://github.com/blumilksoftware/blt/blob/main/src/LaravelContracts.php and try to replicate its purpose here.

2024-06-24 06:56 UTC, krzysztofrewak commented on src/Features/Traits/Eloquent.php
> +     * @Given there is a model :model in the database
All method using tables should have `:` at the end of sentence. Here it's optional, so I would add two sentences.

2024-06-24 06:56 UTC, krzysztofrewak commented on src/Helpers/LaravelRelations.php
> +    public static function assertRelation($instance, string $relation, string $relationType): void
Please type `$instance`. Isn't that Eloquent `Model`?

2024-06-25 08:25 UTC, JakubKermes commented on src/Features/Traits/Eloquent.php
>          $modelClass = $this->recognizeModelClass($model);
Maybe use RecognizeClassHelper instead
```suggestion
        $modelClass = RecognizeClassHelper::recognizeObjectClass($model);
```

2024-06-28 11:46 UTC, krzysztofrewak approved these changes

2024-06-28 11:48 UTC, kamilpiech97 approved these changes

2024-06-28 11:49 UTC, merged