#46 - Update GitHub workflow
blumilksoftware/blt pull request #47
Opened 2024-06-10 15:28 UTC by JakubKermes

Updated workflow based on boilerplate. Introduced minor changes. Now it will also run tests.
This should close #46.

2024-06-11 08:16 UTC, krzysztofrewak requested changes

2024-06-11 08:16 UTC, krzysztofrewak commented on .github/workflows/test-and-lint-php.yml
> +        run: composer test
```suggestion
        run: composer test

```

Please avoid ending files with no empty lines.

2024-06-12 06:25 UTC, Blusia approved these changes

2024-06-12 06:28 UTC, krzysztofrewak approved these changes

2024-06-12 06:41 UTC, merged