#58 add spatielaravel permission tools
blumilksoftware/blt pull request #61
Opened 2024-06-24 13:45 UTC by JakubKermes

This should close #58.
Added options for adding roles and permissions to users, or other objects in database.

2024-06-24 13:50 UTC, JakubKermes commented
This should be working already, but needs eloquent tools to actually implement this into tests, waiting for merge of #42.

2024-07-09 07:07 UTC, krzysztofrewak requested changes
If #70 would be merged before this, you should add some documentation as well.

2024-07-09 07:07 UTC, krzysztofrewak commented on src/Features/Traits/Optional/SpatiePermission.php
> +        Assert::assertTrue(in_array("Spatie\Permission\Traits\HasRoles", $used_traits, true));
```suggestion
        $usedTraits = class_uses_recursive($this->getContainer()->make($objectClass));
        Assert::assertTrue(in_array("Spatie\Permission\Traits\HasRoles", $usedTraits, strict: true));
```

2024-07-09 07:07 UTC, krzysztofrewak commented on src/Features/Traits/Optional/SpatiePermission.php
> +        Assert::assertTrue(in_array("Spatie\Permission\Traits\HasRoles", $used_traits, true));
Plus you could move this class reference to some other file like here: https://github.com/blumilksoftware/blt/blob/main/src/LaravelContracts.php

2024-07-09 07:46 UTC, JakubKermes commented
There is documentation in #70 already for this

2024-07-09 08:05 UTC, merged