#56 - add notification tools
blumilksoftware/blt pull request #62
Opened 2024-06-24 15:01 UTC by JakubKermes

This should close #56.

2024-06-25 10:53 UTC, JakubKermes commented
Works when Notification is sent from test, not when app sends notification. Work in progress

2024-06-27 10:23 UTC, EwelinaSkrzypacz commented
Conflicts :(

2024-06-28 05:17 UTC, EwelinaSkrzypacz commented on src/Features/Traits/Notification.php
> +    }
I think that there is missing method that checks that notification was not sent

2024-06-28 06:45 UTC, EwelinaSkrzypacz approved these changes

2024-06-28 10:39 UTC, krzysztofrewak requested changes

2024-06-28 10:39 UTC, krzysztofrewak commented on src/Features/Traits/Notification.php
> +        $this->getContainer()->instance(ChannelManager::class, $this->notificationFake);
Please use `\Illuminate\Contracts\Notifications\Dispatcher` contract instead of `ChannelManager`.

2024-06-28 11:46 UTC, krzysztofrewak approved these changes

2024-06-28 11:49 UTC, merged