add community standards files
blumilksoftware/blt pull request #83
Opened 2024-07-09 10:16 UTC by JakubKermes

This should close #82.

2024-07-19 12:07 UTC, JakubKermes commented
@krzysztofrewak Should we host website with documentation for BLT?

2024-07-21 09:32 UTC, krzysztofrewak commented
> @krzysztofrewak Should we host website with documentation for BLT?

@JakubKermes, it's hosted in Github Pages: https://blumilksoftware.github.io/blt/

2024-07-23 06:33 UTC, krzysztofrewak requested changes
Please lowercase filenames `changelog.md`, `contributing.md` and rename licencefile to `licence.md`

2024-08-09 05:19 UTC, EwelinaSkrzypacz commented on contributing.md
> +If you find a bug, please open an issue [here](https://github.com/yourusername/yourproject/issues) and include as much detail as possible. Before creating a new issue, please check to see if the bug
```suggestion
If you find a bug, please open an issue [here](https://github.com/blumilksoftware/blt/issues) and include as much detail as possible. Before creating a new issue, please check to see if the bug has already been reported.
```

2024-08-09 05:19 UTC, EwelinaSkrzypacz commented on docs/elements/cookies.html
> +    }"></code-snippet>
```suggestion
    }"></code-snippet>
    
```

2024-08-09 05:19 UTC, EwelinaSkrzypacz commented on docs/elements/hooks.html
> +</article-paragraphs>
```suggestion
</article-paragraphs>

```

2024-08-12 10:40 UTC, EwelinaSkrzypacz commented
Conflicts :eyes:

2024-08-13 05:00 UTC, EwelinaSkrzypacz commented on docs/elements/hooks.html
> +
Now it's to much empty lines on the end of the file :eyes:

2024-08-19 12:33 UTC, EwelinaSkrzypacz approved these changes

2024-08-19 13:14 UTC, krzysztofrewak approved these changes

2024-08-19 16:09 UTC, merged